-- Source-only rollback. Run manually in an isolated database.
BEGIN
  FOR c IN (
    SELECT table_name, column_name FROM user_tab_columns
    WHERE (table_name='BOOKINGS' AND column_name IN
       ('IS_LATE_ENTRY','LATE_ENTRY_REASON','LATE_ENTRY_ENTERED_BY',
        'LATE_ENTRY_ENTERED_AT','BOOKING_PUNCHED_AT','ENTRY_MODE',
        'LATE_ENTRY_TYPE','LATE_ENTRY_REMARKS','IS_LATE_ENTRY_ACTIVATED',
        'LATE_ENTRY_ACTIVATED_BY','LATE_ENTRY_ACTIVATED_AT',
        'POST_TRIP_REASON','ACTUAL_START_AT','ACTUAL_END_AT'))
       OR (table_name='TRIPS' AND column_name IN
       ('CUSTOMER_SIGNATURE_SOURCE','CUSTOMER_SIGNATURE_AT','CUSTOMER_SIGNATURE_BY',
        'DRIVER_SIGNATURE_SOURCE','DRIVER_SIGNATURE_AT','DRIVER_SIGNATURE_BY'))
        OR (table_name='TRIPS' AND column_name IN
       ('DRIVER_FEEDBACK','DRIVER_SAFETY_STATUS','DRIVER_SAFETY_ISSUES',
        'DRIVER_FEEDBACK_SUBMITTED_ON','DRIVER_FEEDBACK_BY'))
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE '||c.table_name||' DROP COLUMN '||c.column_name;
  END LOOP;
END;
/
