-- LAB-only, repeatable trusted Driver device foundation.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name='TRUSTED_DRIVER_DEVICES';
  IF n=0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE trusted_driver_devices (
      device_id VARCHAR2(120) PRIMARY KEY, driver_id VARCHAR2(100) NOT NULL,
      tenant_id VARCHAR2(40) NOT NULL, vendor_id VARCHAR2(40),
      device_key_id VARCHAR2(120) NOT NULL, public_key VARCHAR2(4000) NOT NULL,
      device_name VARCHAR2(200), platform VARCHAR2(30),
      provisioned_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      provisioned_by VARCHAR2(100) NOT NULL, offline_authorized_until TIMESTAMP,
      status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL, revoked_at TIMESTAMP,
      revoked_by VARCHAR2(100), last_online_validation_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)~';
  END IF;
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name='IDX_TRUSTED_DEVICES_DRIVER';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TRUSTED_DEVICES_DRIVER ON TRUSTED_DRIVER_DEVICES(tenant_id,driver_id,status)'; END IF;
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name='UQ_TRUSTED_DEVICE_KEY';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_TRUSTED_DEVICE_KEY ON TRUSTED_DRIVER_DEVICES(device_key_id)'; END IF;
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name='UQ_TRUSTED_DEVICE_PUBLIC_KEY';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_TRUSTED_DEVICE_PUBLIC_KEY ON TRUSTED_DRIVER_DEVICES(public_key)'; END IF;
END;
/
